name: 'Team approval labeler'
description: 'Apply labels to PRs based on team approval'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
